import slugify from '../utils/slugify'

export default {
  title: "Work",
  name: 'work',
  type: "document",
  fields: [
    {
      title: "Title",
      name: "title",
      description: "The name of this work piece, aka eg: 'ID Magazine'",
      type: "string",
    },
    {
      title: "Client",
      name: "client",
      description: "The name of the client this work was done for, eg: 'Loro Piana'",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: 'Category',
      name: 'category',
      description: 'The category of this work piece',
      type: 'reference',
      to: [
        {type: 'categories'}
      ],
      validation: Rule => Rule.required()
    },
    {
      title: "Date",
      name: "date",
      description: "The date of this work, eg: 'February 2021' or ''March - April 2021",
      type: "string",
    },
    {
      title: "Teaser Image",
      name: "teaserImage",
      description: "The image that will be shown as a teaser for this work on the archive page",
      type: "image",
      validation: Rule => Rule.required()
    },
    {
      title: 'Images Carousel',
      name: 'imagesCarousel',
      description: 'The images that will appear on the work carousel, one at a time',
      type: 'array',
      of: [
        {
          name: 'image',
          type: 'image',
          title: 'Image',
          options: {
            hotspot: true,
          },
          fields: [
            {
              name: 'alt',
              type: 'string',
              title: 'Alternative text',
            },
          ],
        },
      ],
      options: {
        layout: 'grid',
      },
      validation: Rule => Rule.required()
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let clientSlug = ''
          let dateSlug = ''
          if (doc.client) {
            clientSlug = `-${doc.client}`
          } else {
            clientSlug = ''
          }

          if (doc.date) {
            dateSlug = `-${doc.date}`
          } else {
            dateSlug = ''
          }

          return `${doc.title}${clientSlug}${dateSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  preview: {
    select: {
      title: 'title',
      client: 'client'
    },
    prepare(selection) {
      const {title, client} = selection
      return {
        title: title,
        subtitle: client
      }
    }
  }
}